# Generated by Django 5.2 on 2025-06-06 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('main_para', models.TextField()),
                ('heading1', models.CharField(blank=True, max_length=100, null=True)),
                ('para1', models.TextField(blank=True, null=True)),
                ('heading2', models.CharField(blank=True, max_length=100, null=True)),
                ('para2', models.TextField(blank=True, null=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
